# Conclusión

Este manual surge de la necesidad detectada de contar con material en español que permita
al usuario aprender a operar un proyecto de datos, más allá del aprendizaje del lenguaje
de programación. A través de cada capitulo, se espera que el lector se familiarice con los
elementos básicos del ambiente de `R`, sus más importantes estructuras de datos, así como
distintas maneras de operarlas. Sin embargo, el enfoque del manual es que el lector cuente
con las herramientas necesarias para poder desarrollar un proyecto de datos.


El manual está estructurado para que en los primeros tres capítulos el lector conozca las
principales herramientas que facilitan el trabajo del analista a través del dominio básico de la
sintaxis de `R`, para, posteriormente, en el capítulo 4, centrarse en el ciclo de análisis de datos.


Para éste ciclo, se revisaron los métodos de importación de datos al ambiente de `R`, la
manipulación y limpieza de datos, revisando a fondo los verbos implementados en `dplyr` y el
concepto de datos limpios, así como su implementación en `tidyr`. Por último, para concluir el
ciclo de análisis se mostró una introducción a la gramática de gráficas y su implementación en
`ggplot2`. Se utilizó la conjugación de los verbos de `dplyr`, pues estos permiten realizar casi
todas las operaciones que un analista debe realizar para preparar sus datos para el modelado,
facilitando su visualización o presentación en formato tabular, así como permitir la realización
de estadística 


Por último, con la finalidad de que el lector pueda practicar lo aprendido se incluyeron
múltiples ejercicios y referencias a otro tipo de herramientas que salen del alcance de este
manual pero que complementan al material presentado, como lo son, las expresiones regulares,
el trabajo con fechas, la manipulación de cadenas de caracteres, entre otros.


A través de diversas iteraciones con distintos grupos, el material ha probado ser útil como
guía en varios cursos introductorios a `R`, cumpliendo con el objetivo o alcance del mismo.


Con la finalidad de fortalecer el presente manual, así como seguir construyendo material en
español que permita el desarrollo de proyectos de datos cada vez más sólidos, es posible ampliar
el material de manera que se cubran distintas herramientas para el modelado, particularmente
las implementadas en `purrr` que continúan con el *framework* de datos limpios para esta etapa
en el ciclo de análisis; así como ahondar en el apartado de comunicación, que solo se cubrió 
en el capítulo 2 presentando `rmarkdown` para compilar documentos reproducibles, así como
traducir los cursos de `swirl` a los que se hace referencia.


En este sentido, se invita a que el lector proporcione comentarios y sugerencias para mejorar
o ampliar el material a través de *issues* o *pull requests* en el repositorio del proyecto:
[https://github.com/animalito/aprendeR](https://github.com/animalito/aprendeR).